# Generated by Django 4.1.2 on 2023-03-04 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
