# Generated by Django 4.1.2 on 2023-03-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
