# Generated by Django 4.1.1 on 2022-10-10 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0002_alter_table_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'unique_together': {('category_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Processing', 'Processing'), ('Completed', 'Completed')], max_length=255)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('pay', models.BooleanField(default=False)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.item')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.table')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField()),
                ('pay', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.table')),
            ],
            options={
                'verbose_name': 'bill',
                'verbose_name_plural': 'bills',
            },
        ),
    ]
