# Generated by Django 4.1.2 on 2022-10-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0006_alter_bill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Waiting', max_length=255),
        ),
    ]
