# Generated by Django 4.1.2 on 2022-11-08 04:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0008_order_bill_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='all_api.bill'),
        ),
    ]
