# Generated by Django 4.1.7 on 2023-03-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_is_completed_alter_order_status'),
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='orders',
            field=models.ManyToManyField(related_name='orders_for_bill', to='order.order', verbose_name='orders'),
        ),
    ]
