# Generated by Django 4.1.7 on 2023-03-25 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_forgotpasswordtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
