# Generated by Django 4.1.7 on 2023-03-28 10:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('table', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Prepairing', 'Prepairing'), ('Cooked', 'Cooked')], default='Waiting', max_length=10, verbose_name='status')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is completed')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_for_order', to='item.item', verbose_name='item')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='table_for_order', to='table.table', verbose_name='table')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created_at',),
            },
        ),
    ]
