# Generated by Django 4.1.7 on 2023-03-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Prepairing', 'Prepairing'), ('Cooked', 'Cooked'), ('Delivered', 'Delivered')], default='Waiting', max_length=10, verbose_name='status'),
        ),
    ]
